### ISSUE TITLE
Which game platform?

### ISSUE THREAD

**Issue by zbeucler2018** [Sewer56/Sewer56.SonicRiders#3]
Hello! First off, this is an awesome repo for an awesome game. 

Which platform does this mod work for? Do I need to use a emulator like PSX?

**Comment by Sewer56** [comment]
This isn't a mod. This is a library (collection of code) to help making modding the PC version of Sonic Riders easier for programmers. That's about it :p

**Comment by zbeucler2018** [comment]
Thank u!!
